// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetAllMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMetricsRequest) Reset() {
	*x = GetAllMetricsRequest{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMetricsRequest) ProtoMessage() {}

func (x *GetAllMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetAllMetricsRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllMetricsRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetAllMetricsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Error          string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	GaugeMetrics   []*Metric              `protobuf:"bytes,2,rep,name=gauge_metrics,json=gaugeMetrics,proto3" json:"gauge_metrics,omitempty"`
	CounterMetrics []*Metric              `protobuf:"bytes,3,rep,name=counter_metrics,json=counterMetrics,proto3" json:"counter_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAllMetricsResponse) Reset() {
	*x = GetAllMetricsResponse{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMetricsResponse) ProtoMessage() {}

func (x *GetAllMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetAllMetricsResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllMetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetAllMetricsResponse) GetGaugeMetrics() []*Metric {
	if x != nil {
		return x.GaugeMetrics
	}
	return nil
}

func (x *GetAllMetricsResponse) GetCounterMetrics() []*Metric {
	if x != nil {
		return x.CounterMetrics
	}
	return nil
}

type UpdateMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricRequest) Reset() {
	*x = UpdateMetricRequest{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricRequest) ProtoMessage() {}

func (x *UpdateMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMetricRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type UpdateMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UpdatedMetric *Metric                `protobuf:"bytes,2,opt,name=updated_metric,json=updatedMetric,proto3" json:"updated_metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricResponse) Reset() {
	*x = UpdateMetricResponse{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricResponse) ProtoMessage() {}

func (x *UpdateMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMetricResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateMetricResponse) GetUpdatedMetric() *Metric {
	if x != nil {
		return x.UpdatedMetric
	}
	return nil
}

type UpdateMetricsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestMetrics []*Metric              `protobuf:"bytes,1,rep,name=request_metrics,json=requestMetrics,proto3" json:"request_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMetricsRequest) Reset() {
	*x = UpdateMetricsRequest{}
	mi := &file_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsRequest) ProtoMessage() {}

func (x *UpdateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMetricsRequest) GetRequestMetrics() []*Metric {
	if x != nil {
		return x.RequestMetrics
	}
	return nil
}

type UpdateMetricsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Error          string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UpdatedMetrics []*Metric              `protobuf:"bytes,2,rep,name=updated_metrics,json=updatedMetrics,proto3" json:"updated_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMetricsResponse) Reset() {
	*x = UpdateMetricsResponse{}
	mi := &file_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsResponse) ProtoMessage() {}

func (x *UpdateMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricsResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateMetricsResponse) GetUpdatedMetrics() []*Metric {
	if x != nil {
		return x.UpdatedMetrics
	}
	return nil
}

type GetMetricByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricByNameRequest) Reset() {
	*x = GetMetricByNameRequest{}
	mi := &file_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricByNameRequest) ProtoMessage() {}

func (x *GetMetricByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricByNameRequest.ProtoReflect.Descriptor instead.
func (*GetMetricByNameRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *GetMetricByNameRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetMetricByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMetricByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Metric        *Metric                `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricByNameResponse) Reset() {
	*x = GetMetricByNameResponse{}
	mi := &file_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricByNameResponse) ProtoMessage() {}

func (x *GetMetricByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricByNameResponse.ProtoReflect.Descriptor instead.
func (*GetMetricByNameResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *GetMetricByNameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetMetricByNameResponse) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\ametrics\"X\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\",\n" +
	"\x14GetAllMetricsRequest\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x9d\x01\n" +
	"\x15GetAllMetricsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x124\n" +
	"\rgauge_metrics\x18\x02 \x03(\v2\x0f.metrics.MetricR\fgaugeMetrics\x128\n" +
	"\x0fcounter_metrics\x18\x03 \x03(\v2\x0f.metrics.MetricR\x0ecounterMetrics\">\n" +
	"\x13UpdateMetricRequest\x12'\n" +
	"\x06metric\x18\x01 \x01(\v2\x0f.metrics.MetricR\x06metric\"d\n" +
	"\x14UpdateMetricResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x126\n" +
	"\x0eupdated_metric\x18\x02 \x01(\v2\x0f.metrics.MetricR\rupdatedMetric\"P\n" +
	"\x14UpdateMetricsRequest\x128\n" +
	"\x0frequest_metrics\x18\x01 \x03(\v2\x0f.metrics.MetricR\x0erequestMetrics\"g\n" +
	"\x15UpdateMetricsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x128\n" +
	"\x0fupdated_metrics\x18\x02 \x03(\v2\x0f.metrics.MetricR\x0eupdatedMetrics\"@\n" +
	"\x16GetMetricByNameRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"X\n" +
	"\x17GetMetricByNameResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12'\n" +
	"\x06metric\x18\x02 \x01(\v2\x0f.metrics.MetricR\x06metric2\xcc\x02\n" +
	"\aMetrics\x12N\n" +
	"\rGetAllMetrics\x12\x1d.metrics.GetAllMetricsRequest\x1a\x1e.metrics.GetAllMetricsResponse\x12K\n" +
	"\fUpdateMetric\x12\x1c.metrics.UpdateMetricRequest\x1a\x1d.metrics.UpdateMetricResponse\x12N\n" +
	"\rUpdateMetrics\x12\x1d.metrics.UpdateMetricsRequest\x1a\x1e.metrics.UpdateMetricsResponse\x12T\n" +
	"\x0fGetMetricByName\x12\x1f.metrics.GetMetricByNameRequest\x1a .metrics.GetMetricByNameResponseB\x0fZ\rmetrics/protob\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_metrics_proto_goTypes = []any{
	(*Metric)(nil),                  // 0: metrics.Metric
	(*GetAllMetricsRequest)(nil),    // 1: metrics.GetAllMetricsRequest
	(*GetAllMetricsResponse)(nil),   // 2: metrics.GetAllMetricsResponse
	(*UpdateMetricRequest)(nil),     // 3: metrics.UpdateMetricRequest
	(*UpdateMetricResponse)(nil),    // 4: metrics.UpdateMetricResponse
	(*UpdateMetricsRequest)(nil),    // 5: metrics.UpdateMetricsRequest
	(*UpdateMetricsResponse)(nil),   // 6: metrics.UpdateMetricsResponse
	(*GetMetricByNameRequest)(nil),  // 7: metrics.GetMetricByNameRequest
	(*GetMetricByNameResponse)(nil), // 8: metrics.GetMetricByNameResponse
}
var file_metrics_proto_depIdxs = []int32{
	0,  // 0: metrics.GetAllMetricsResponse.gauge_metrics:type_name -> metrics.Metric
	0,  // 1: metrics.GetAllMetricsResponse.counter_metrics:type_name -> metrics.Metric
	0,  // 2: metrics.UpdateMetricRequest.metric:type_name -> metrics.Metric
	0,  // 3: metrics.UpdateMetricResponse.updated_metric:type_name -> metrics.Metric
	0,  // 4: metrics.UpdateMetricsRequest.request_metrics:type_name -> metrics.Metric
	0,  // 5: metrics.UpdateMetricsResponse.updated_metrics:type_name -> metrics.Metric
	0,  // 6: metrics.GetMetricByNameResponse.metric:type_name -> metrics.Metric
	1,  // 7: metrics.Metrics.GetAllMetrics:input_type -> metrics.GetAllMetricsRequest
	3,  // 8: metrics.Metrics.UpdateMetric:input_type -> metrics.UpdateMetricRequest
	5,  // 9: metrics.Metrics.UpdateMetrics:input_type -> metrics.UpdateMetricsRequest
	7,  // 10: metrics.Metrics.GetMetricByName:input_type -> metrics.GetMetricByNameRequest
	2,  // 11: metrics.Metrics.GetAllMetrics:output_type -> metrics.GetAllMetricsResponse
	4,  // 12: metrics.Metrics.UpdateMetric:output_type -> metrics.UpdateMetricResponse
	6,  // 13: metrics.Metrics.UpdateMetrics:output_type -> metrics.UpdateMetricsResponse
	8,  // 14: metrics.Metrics.GetMetricByName:output_type -> metrics.GetMetricByNameResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
